import { AirportModel, CountryModel } from "./types";

export const countries: CountryModel[] = [
  { id: 1, name: "Poland" },
  { id: 2, name: "Spain" },
];

export const airports: AirportModel[] = [
  {
    id: 1,
    name: "Wrocław Airport",
    iata: "WRO",
    cities: "Wrocław",
    country_id: 1,
    airlines: [1, 2, 4, 5],
    services: [1, 3, 4, 5, 6],
  },
  {
    id: 2,
    name: "Warsaw Chopin",
    iata: "WAW",
    cities: "Warszawa",
    country_id: 1,
    airlines: [1, 2, 4, 5],
    services: [1, 2, 3, 4, 5, 6, 7],
  },
  {
    id: 3,
    name: "Warsaw Modlin",
    iata: "WMI",
    cities: "Warszawa",
    country_id: 1,
    airlines: [4],
    services: [4, 6],
  },
  {
    id: 4,
    name: "Lotnisko Radom",
    iata: "RDO",
    cities: "Radom, Warszawa, Kielce",
    country_id: 1,
    airlines: [1],
    services: [],
  },
  {
    id: 11,
    name: "Barcelona El-Prat",
    iata: "BCN",
    cities: "Barcelona",
    country_id: 2,
    airlines: [2, 3, 4, 5, 6],
    services: [1, 2, 3, 4, 5, 7],
  },
  {
    id: 12,
    name: "Palma Mallorca",
    iata: "PMI",
    cities: "Mallorca Island",
    country_id: 2,
    airlines: [2, 3, 4, 6],
    services: [1, 3, 4, 5, 7],
  },
  {
    id: 13,
    name: "Sevilla",
    iata: "SVQ",
    cities: "Sevilla",
    country_id: 2,
    airlines: [2, 3, 4, 6],
    services: [1, 2, 4, 5, 6],
  },
  {
    id: 14,
    name: "Tenerife Norte",
    iata: "TFN",
    cities: "Santa Cruz De Tenerife, Tenerife domestic",
    country_id: 2,
    airlines: [3, 6],
    services: [1, 4, 5, 6],
  },
  {
    id: 15,
    name: "Tenerife Reina Sofia",
    iata: "TFS",
    cities: "Tenerife Island",
    country_id: 2,
    airlines: [2, 3, 4, 5],
    services: [1, 4, 5],
  },
];
